import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { MantineProvider } from "@mantine/core";
import '@mantine/core/styles.css'
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/exif-js/2.3.0/exif.js"></script>
        <Header />
        <MantineProvider>
          {children}
        </MantineProvider>
        
        <div className="BodyWrapper">
          <Header />
          <MantineProvider>
            {children}
          </MantineProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
